# -*- coding: utf-8 -*-

from odoo.tools.translate import _

header = {
    'Order Item Id': 'order_item_id',
    'Order Type': 'order_type',
    'Order Flag': 'order_flag',
    'Lazada Id': 'lazada_id',
    'Seller SKU': 'seller_sku',
    'Lazada SKU': 'lazada_sku',
    'Created at': 'created_at',
    'Updated at': 'updated_at',
    'Order Number': 'order_number',
    'Invoice Required': 'invoice_required',
    'Customer Name': 'customer_name',
    'Customer Email': 'customer_email',
    'National Registration Number': 'national_registration_number',
    'Shipping Name': 'shipping_name',
    'Shipping Address': 'shipping_address',
    'Shipping Address2': 'shipping_address2',
    'Shipping Address3': 'shipping_address3',
    'Shipping Address4': 'shipping_address4',
    'Shipping Address5': 'shipping_address5',
    'Shipping Phone Number': 'shipping_phone_number',
    'Shipping Phone Number2': 'shipping_phone_number2',
    'Shipping City': 'shipping_city',
    'Shipping Postcode': 'shipping_postcode',
    'Shipping Country': 'shipping_country',
    'Shipping Region': 'shipping_region',
    'Billing Name': 'billing_name',
    'Billing Address': 'billing_address',
    'Billing Address2': 'billing_address2',
    'Billing Address3': 'billing_address3',
    'Billing Address4': 'billing_address4',
    'Billing Address5': 'billing_address5',
    'Billing Phone Number': 'billing_phone_number',
    'Billing Phone Number2': 'billing_phone_number2',
    'Billing City': 'billing_city',
    'Billing Postcode': 'billing_postcode',
    'Billing Country': 'billing_country',
    'Tax Code': 'tax_code',
    'Branch Number': 'branch_number',
    'Tax Invoice requested': 'tax_invoice_requested',
    'Payment Method': 'payment_method',
    'Paid Price': 'paid_price',
    'Unit Price': 'unit_price',
    'Shipping Fee': 'shipping_fee',
    'Wallet Credits': 'wallet_credits',
    'Item Name': 'item_name',
    'Variation': 'variation',
    'CD Shipping Provider': 'cd_shipping_provider',
    'Shipping Provider': 'shipping_provider',
    'Shipment Type Name': 'shipment_type_name',
    'Shipping Provider Type': 'shipping_provider_type',
    'CD Tracking Code': 'cd_tracking_code',
    'Tracking Code': 'tracking_code',
    'Tracking URL': 'tracking_url',
    'Shipping Provider (first mile)': 'shipping_provider_first_mile',
    'Tracking Code (first mile)': 'tracking_code_first_mile',
    'Tracking URL (first mile)': 'tracking_url_first_mile',
    'Promised shipping time': 'promised_shipping_time',
    'Premium': 'premium',
    'Status': 'status',
    'Cancel / Return Initiator': 'cancel_return_initiator',
    'Reason': 'reason',
    'Reason Detail': 'reason_detail',
    'Editor': 'editor',
    'Bundle ID': 'bundle_id',
    'Bundle Discount': 'bundle_discount',
    'Refund Amount': 'refund_amount'
}